version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - buithaibinh
    reviewers:
      - buithaibinh
    labels:
      - dependencies
      - automated
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
