name: Build & test

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  build_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Format check
        run: npm run lint

      - name: Format code
        run: npm run format

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Publish to npm
        if: github.ref == 'refs/heads/release'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
